// src/lib/product-bbox.js
// Pre-computed opacity bounding boxes for product images
// Generated by: node scripts/compute-bbox.mjs

/** @type {Record<string, {top: number, right: number}>} */
export const PRODUCT_BBOX = {
  "/products/gray.png": {
    "top": 0.1488,
    "right": 0.0861
  },
  "/products/brown.png": {
    "top": 0.1063,
    "right": 0.0923
  },
  "/products/black.png": {
    "top": 0.1048,
    "right": 0.0979
  },
  "/products/green.png": {
    "top": 0.1055,
    "right": 0.1029
  },
  "/products/blue.png": {
    "top": 0.1048,
    "right": 0.0861
  }
}
